// function Person(name) {
//   this.name = name;
//   this.friends = [];
// }
//
// Person.prototype.addFriend = function(friend) {
//   this.friends.push(friend);
// };
//
// Person.prototype.createGreeting = function(other) {
//   return 'Yo ' + other.name + '! from ' + this.name + '.';
// };
//
// Person.prototype.greet = function(other) {
//   console.log(this.createGreeting(other));
// };

class Person {
  constructor(name) {
    this.name = name;
    this.friends = [];
  };

  addFriend(friend) {
    this.friends.push(friend);
  };

  createGreeting(other) {
    return 'Yo ' + other.name + '! from ' + this.name + '.';
  };

  greet(other) {
    console.log(this.createGreeting(other));
  };
// These thises
// Given the Person type given in the last problem, add to it a lazyGreet
// method which will print out the same greeting message but only after
// 2 seconds.
  lazyGreet(other) {
    // var self = this;
    setTimeout(() => { this.greet(other) }, 2000);
  };
};


// These thises 2
//
// Add to Person a createGreetingsForFriends method which will return an array of strings - each string in the array is a greeting generated by the createGreeting method. For example:
//
// > var alfie = new Person('Alfie');
// > var anushka = new Person('Anushka');
// > var henrique = new Person('Henrique');
// > alfie.addFriend(anushka);
// > alfie.addFriend(henrique);
// > alfie.createGreetingsForFriends();
// ["Yo Anushka! from Alfie.", "Yo Henrique! from Alfie."]
// Do this without using a loop but by using map instead.

var monis = new Person('Monis');
var paul = new Person('Paul');
monis.lazyGreet(paul);
